ToDoList/ToDoList/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('agenda.urls')),
]

ToDoList/agenda/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views

app_name = "agenda"

urlpatterns = [
    path('', views.index, name = 'index'),
    path('signup/',views.signup,name="signup"),
    path('login/', views.login, name='login'),
    path('logout/',views.logout, name = "logout"),
    path('detail/',views.details, name = 'detail'),
]

ToDoList/agenda/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class ToDos(models.Model):
    content = models.CharField(max_length=200)
    pub_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete = models.CASCADE, default = '')



    

ToDoList/agenda/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email=forms.EmailField(label="이메일")
    class Meta:
        model = User
        fields=('username','password1','password2','email')

ToDoList/agenda/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from .forms import UserForm
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from .models import ToDos
# Create your views here.
def index(request):
    return render(request, 'agenda/index.html')



def signup(request):
    if request.method=="POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('agenda:index')

        else:
            return render(request,'agenda/signup.html',{'form':form})
    else:
        form = UserForm()
        return render(request,'agenda/signup.html',{'form':form})


def login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username = username, password = password)
        if user is not None:
            auth_login(request, user)
            return redirect('agenda:detail')
        else:
            return redirect('agenda:login')
           
        
    else:
        return render(request, 'agenda/login.html')
    
def logout(request):
    auth_logout(request)
    return redirect("agenda:index")



@login_required(login_url = 'agenda:index')
def details(request):
    # 여기가 아마 진용님이 작업하실 뷰 인것같습니다. 여기서 초기화면 구현 로직 짜시면 됩니다! 저엿다면 objects.get(유저정보)로 데이터목록들을 불러올거같습니다!
    # url pattern과 function 이름도 제가 마음대로 햇으니 마음대로 수정하셔도 됩니다! 진용님파트가 제일 중요할거같네요ㅎㅎ HTML도 새로 만들어야될거같습니다. 추가로 settings.py파일에 login_redirect_url도 수정이 필요할거같습니다
    user = request.user
    return render (request, 'agenda/details.html', {'user': user})


def update(request):
    #학선님 업데이트 뷰 입니다! 제 생각에는 업데이트 버튼 클릭 시 pk 를 이용한 데이터조회후에 create form 으로 간 다음 request.method == "POST" 로 데이터 수정 가능할것같습니다!
    return

def delete(request):
    #선우님 삭제 뷰 입니다! 업데이트와 비슷하게 클릭 시 pk를 이용한 데이터 조회후에 삭제. 따로 render html파일은 안만들어도 될거 같습니다! redirect로!
    data=get_object_or_404(ToDos,pk=id)
    data.delete()
    return redirect('agenda/details.html')

def create(request):
    #은혜님 뷰! 제 생각에 createform.html 파일을 만들어야할거같습니다. 또 forms.py파일에 새로운 클래스와 데이터베이스 연동이 필요할듯합니다! 
    return

ToDoList/templates/agenda/createform.html
{% extends 'base.html' %}
{% block content %}
<h2>todolist 추가</h2>
<form method = "POST">
    {% csrf_token %}
    <br>
    <textarea name="content" cols="15" rows="15">{{ form.content.value | default_if_none:"" }}</textarea>
    <br>
    <input type="submit" value="Send">
</form>
{% endblock %}

ToDoList/templates/agenda/details.html
{% extends 'base.html' %}
{% block content %}
<h1> Hello {{user.username}}</h1>
<a href = "{% url 'agenda:logout' %}">로그아웃</a>



{% endblock %}

ToDoList/templates/agenda/index.html
{% extends 'base.html' %}
{% block content %}
<h1>Welcome to Techeer Partners H Team ToDoList</h1>
<div>
    <h2> Please login to view your to-do list</h2>
</div>
<div>
    <p>김진뇽</p>
    <form method = "GET" action = "{% url 'agenda:login' %}">
    <input type ="submit" Value = '로그인'>
</form>
<p>Don't have an account? Click</p><a href="{% url 'agenda:signup' %}">here</a><p>to signup!</p>
</div>
{%endblock%}

ToDoList/templates/agenda/login.html
{% extends 'base.html' %}
{% block content %}
<div>
    <h1>로그인</h1>
     
    <form method = "POST" action = "{% url 'agenda:login' %}">
        {%csrf_token%}
        Username:
        <br>
        <input name = "username" type = "text">
        <br>
        Password:
        <br>
        <input name = "password" type = "password">
        <br><br>
        <input type = "submit" value = "로그인">
    </form>
{% for message in messages %}
    <div>
        {{mesage}}
</div>
{% endfor %}
{% endblock %}

ToDoList/templates/agenda/signup.html
{% extends 'base.html' %}
{% block content %}
<div>
    <form method="post" action="{% url 'agenda:signup' %}">
        {% csrf_token %}
        {{form.as_div}}
        <button type="submit"> 생성하기</button>
    </form>
</div>
{% endblock %}

ToDoList/templates/base.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   <title>H-Team ToDoList</title>
</head>
<body>
    {%block content%}
    {%endblock%}

</body>
</html>